# Generated by Django 3.2 on 2022-01-18 12:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('construction_type', models.CharField(choices=[('1', 'Residential'), ('2', 'Historical'), ('3', 'Another')], default='3', max_length=1)),
                ('height', models.DecimalField(decimal_places=2, max_digits=100)),
                ('floor_number', models.IntegerField(default=1)),
                ('build_date', models.DateField()),
                ('total_area', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=3, max_digits=100)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('acoustic_analysis', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('vibration', models.DecimalField(blank=True, decimal_places=3, max_digits=100)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.construction')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='building.measurement')),
                ('foundation_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('floor_mark', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6)),
                ('walls_mark', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6)),
                ('roof_mark', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6)),
                ('construction_reliability', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
                ('construction_damage', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
                ('final_coefficient', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('construction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='building.construction')),
                ('floor_type', models.CharField(choices=[('1', 'Wood'), ('2', 'Brick'), ('3', 'Vinyl'), ('4', 'Metal'), ('5', 'Stone'), ('6', 'Concrete'), ('7', 'Plastic'), ('8', 'Another')], default='8', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('construction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='building.construction')),
                ('area', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100)),
                ('foundation_type', models.CharField(choices=[('1', 'Strip'), ('2', 'Columnar'), ('3', 'Pile'), ('4', 'Panel-wall'), ('5', 'Screw'), ('6', 'Another')], default='6', max_length=20)),
                ('foundation_material', models.CharField(choices=[('1', 'Wood'), ('2', 'Brick'), ('3', 'Vinyl'), ('4', 'Metal'), ('5', 'Stone'), ('6', 'Concrete'), ('7', 'Plastic'), ('8', 'Another')], default='8', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('construction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='building.construction')),
                ('roof_type', models.CharField(choices=[('1', 'Gable'), ('2', 'Hip'), ('3', 'Dutch'), ('4', 'Mansard'), ('5', 'Flat'), ('6', 'Shed'), ('7', 'Butterfly'), ('8', 'Gambrel'), ('9', 'Dormer'), ('10', 'M Shaped'), ('11', 'Combined')], default='11', max_length=20)),
                ('roof_material', models.CharField(choices=[('1', 'Wood'), ('2', 'Brick'), ('3', 'Vinyl'), ('4', 'Metal'), ('5', 'Stone'), ('6', 'Concrete'), ('7', 'Plastic'), ('8', 'Another')], default='8', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Walls',
            fields=[
                ('construction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='building.construction')),
                ('walls_material', models.CharField(choices=[('1', 'Wood'), ('2', 'Brick'), ('3', 'Vinyl'), ('4', 'Metal'), ('5', 'Stone'), ('6', 'Concrete'), ('7', 'Plastic'), ('8', 'Another')], default='8', max_length=1)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('years_until_full_fix', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100)),
                ('years_until_full_warning', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100)),
                ('construction_damage_predicted', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=100), size=None)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.construction')),
            ],
        ),
    ]
